### ISSUE TITLE
Add support for items management

### ISSUE THREAD

**Issue by guillerglez88** [guillerglez88/ScioRPG#3]
Enable support for items creation via UI.

- [x] Persistent state
- [x] List items
- [x] Create
- [x] Edit
- [x] Remove

**Comment by pedro-ramirez-suarez** [comment]
Question from Scio: why did you replaced the old implementation(the one with a base class and independent implementations for each item and character), please comment advantages and disadvantages with the previous approach.

**Comment by guillerglez88** [comment]
Will move the above comment :point_up_2:, to PR #2.

**Comment by guillerglez88** [comment]
@pedro-ramirez-suarez do you want me to open another issue to discuss it on?

**Comment by pedro-ramirez-suarez** [comment]
no, it's ok.

**Comment by guillerglez88** [comment]
# List

![image](https://cloud.githubusercontent.com/assets/8441801/16571589/257b95b8-422d-11e6-845d-6fced83dd22c.png)

# Actions
![image](https://cloud.githubusercontent.com/assets/8441801/16571596/51d3b5f0-422d-11e6-823e-0fe7fb305430.png)

# Create

![image](https://cloud.githubusercontent.com/assets/8441801/16571614/97bf5268-422d-11e6-9056-c81b3eda14d2.png)

# Edit

![image](https://cloud.githubusercontent.com/assets/8441801/16571609/7aa9226c-422d-11e6-98e2-09933981a7a9.png)

# Delete

![image](https://cloud.githubusercontent.com/assets/8441801/16571633/c41794c4-422d-11e6-83a8-3aaadf3f0de4.png)
